[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  GO_VERSION = "1.19"

# Redirects for single-page application
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 